<?php

namespace App\Filament\Widgets;

use Filament\Support\RawJs;
use Filament\Widgets\ChartWidget;
use Illuminate\Contracts\Support\Htmlable;

class InsideChart extends ChartWidget
{
    protected static ?string $heading = 'Inside & Outside Chart';
    public function getHeading(): string|Htmlable|null
    {
        return __('Inside & Outside Chart'); // TODO: Change the autogenerated stub

    }


    protected function getData(): array
    {
        $inside = \App\Models\Attendance::where('attend', 1)
            ->whereHas('meeting', fn ($q) => $q->where('inside', 1))
            ->count();

        $outside = \App\Models\Attendance::where('attend', 1)
            ->whereHas('meeting', fn ($q) => $q->where('inside', 0))
            ->count();

        return [
            'datasets' => [
                [
                    'label' => __('Attendance (Inside vs Outside)'),
                    'data' => [$inside, $outside],
                ],
            ],
            'labels' => [ __('Inside Meetings'), __('Outside Meetings')],
        ];
    }

    protected function getType(): string
    {
        return 'pie';
    }

    protected function getOptions(): array|RawJs|null
    {
        return [
            'scales' => [
                'x' => [
                    'display' => false,
                ],
                'y' => [
                    'display' => false,
                ],
            ],
            'maintainAspectRatio' => false,

            'plugins' => [
                'legend' => [
                    'position' => 'bottom',
                ],
            ],
            'backgroundColor' => [
                '#4CAF50', // Green
                '#F44336', // Red
                '#2196F3', // Blue
                '#FFC107', // Yellow
            ],
        ];
    }
//    public function getColumnSpan(): int|string|array
//    {
//        return [
//            'default' => 3,   // نص الشاشة
//            'xl' => 3,
//        ];
//    }

}
