<?php

namespace App\Filament\Widgets;

use Filament\Widgets\ChartWidget;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Facades\DB;

class MostAttendChart extends ChartWidget
{
    protected static ?string $heading = 'Most Attend Chart';

    public function getHeading(): string|Htmlable|null
    {
        return __('Most Attend Chart'); // TODO: Change the autogenerated stub
    }

    protected function getData(): array
    {
        $topStudents = \App\Models\Attendance::where('attend', 1)
            ->select('user_id', DB::raw('COUNT(*) as total'))
            ->groupBy('user_id')
            ->orderByDesc('total')
            ->with('student:id,name') // load student name
            ->limit(10)
            ->get();
        return [
            'datasets' => [
                [
                    'label' => __('Top 10 Students Attendance'),
                    'data' => $topStudents->pluck('total')->toArray(),
                ],
            ],
            'labels' => $topStudents->pluck('student.name')->toArray(),
        ];
    }

    protected function getType(): string
    {
        return 'bar';
    }
}
