<?php

namespace App\Filament\Widgets;

use Filament\Widgets\ChartWidget;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Facades\DB;

class MostMeetingChart extends ChartWidget
{
    protected static ?string $heading = 'Most Meetings Attend Chart';

    public function getHeading(): string|Htmlable|null
    {
        return __('Most Meetings Attend Chart'); // TODO: Change the autogenerated stub
    }


    protected function getData(): array
    {
        $topStudents = \App\Models\Attendance::where('attend', 1)
            ->select('meeting_id', DB::raw('COUNT(*) as total'))
            ->groupBy('meeting_id')
            ->orderByDesc('total')
            ->with('meeting:id,title') // load student name
            ->limit(10)
            ->get();
        return [
            'datasets' => [
                [
                    'label' => __('Top 10 Meetings Attendance'),
                    'data' => $topStudents->pluck('total')->toArray(),
                ],
            ],
            'labels' => $topStudents->pluck('meeting.title')->toArray(),
        ];    }

    protected function getType(): string
    {
        return 'bar';
    }
}
